export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CLERK_ID_MISMATCH: "CLERK_ID_MISMATCH",
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  CONFLICT: "CONFLICT",
  RESERVATION_INVALID: "RESERVATION_INVALID",
  SLUG_TAKEN: "SLUG_TAKEN",
  IDEMPOTENCY_LOCKED: "IDEMPOTENCY_LOCKED",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // Workspace: Slug Service
  WORKSPACE_SLUG_RATE_LIMITED: "WORKSPACE_SLUG_RATE_LIMITED",
  WORKSPACE_SLUG_TAKEN_PERMANENT: "WORKSPACE_SLUG_TAKEN_PERMANENT",
  WORKSPACE_SLUG_TAKEN_RESERVED: "WORKSPACE_SLUG_TAKEN_RESERVED",
  WORKSPACE_SLUG_RESERVATION_FAILED: "WORKSPACE_SLUG_RESERVATION_FAILED",

  // Workspace: Creation Service
  WORKSPACE_CREATION_RESERVATION_MISSING:
    "WORKSPACE_CREATION_RESERVATION_MISSING",
  WORKSPACE_CREATION_RESERVATION_STOLEN:
    "WORKSPACE_CREATION_RESERVATION_STOLEN",
  WORKSPACE_CREATION_DB_CONFLICT: "WORKSPACE_CREATION_DB_CONFLICT",
  WORKSPACE_CREATION_QUOTA_EXCEEDED: "WORKSPACE_CREATION_QUOTA_EXCEEDED",

  // Workspace: Onboarding Service
  WORKSPACE_ONBOARDING_ALREADY_EXISTS: "WORKSPACE_ONBOARDING_ALREADY_EXISTS",
  WORKSPACE_ONBOARDING_SLUG_GENERATION_FAILED:
    "WORKSPACE_ONBOARDING_SLUG_GENERATION_FAILED",
  WORKSPACE_ONBOARDING_CUSTOM_SLUG_TAKEN:
    "WORKSPACE_ONBOARDING_CUSTOM_SLUG_TAKEN",

  // Notification Service
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
  INVALID_EVENT_PAYLOAD: "INVALID_EVENT_PAYLOAD",
  NOTIFICATION_PROVIDER_ERROR: "NOTIFICATION_PROVIDER_ERROR", // Generic Provider Error

  // Decider Service
  DECIDER_TYPE_UNKNOWN: "DECIDER_TYPE_UNKNOWN",
  DECIDER_STRATEGY_VIOLATION: "DECIDER_STRATEGY_VIOLATION",
  DECIDER_SCHEMA_MISSING: "DECIDER_SCHEMA_MISSING",

  // Queue / BullMQ
  QUEUE_CONNECTION_FAILED: "QUEUE_CONNECTION_FAILED",
  QUEUE_JOB_STALLED: "QUEUE_JOB_STALLED",
  QUEUE_JOB_FAILED: "QUEUE_JOB_FAILED",

  // Email Provider
  EMAIL_PROVIDER_RATE_LIMIT: "EMAIL_PROVIDER_RATE_LIMIT",
  EMAIL_TEMPLATE_INVALID: "EMAIL_TEMPLATE_INVALID",

  // Workspace: Invitation
  INVITE_NOT_FOUND: "INVITE_NOT_FOUND",
  INVITE_EXPIRED: "INVITE_EXPIRED",
  ALREADY_WORKSPACE_MEMBER: "ALREADY_WORKSPACE_MEMBER",

  // Chat: Channel Locking
  CHANNEL_NAME_TAKEN_PERMANENT: "CHANNEL_NAME_TAKEN_PERMANENT",
  CHANNEL_NAME_RESERVATION_FAILED: "CHANNEL_NAME_RESERVATION_FAILED",
  CHANNEL_NAME_RESERVATION_STOLEN: "CHANNEL_NAME_RESERVATION_STOLEN",

  // Project: Slug Service
  PROJECT_SLUG_RATE_LIMITED: "PROJECT_SLUG_RATE_LIMITED",
  PROJECT_SLUG_TAKEN_PERMANENT: "PROJECT_SLUG_TAKEN_PERMANENT",
  PROJECT_SLUG_TAKEN_RESERVED: "PROJECT_SLUG_TAKEN_RESERVED",
  PROJECT_SLUG_RESERVATION_FAILED: "PROJECT_SLUG_RESERVATION_FAILED",

  // Project: Creation Service
  PROJECT_CREATION_QUOTA_EXCEEDED: "PROJECT_CREATION_QUOTA_EXCEEDED",
  PROJECT_CREATION_MISSING_PERMISSION: "PROJECT_CREATION_MISSING_PERMISSION",
  PROJECT_CREATION_FAILED: "PROJECT_CREATION_FAILED",
  PROJECT_CREATION_RESERVATION_STOLEN: "PROJECT_CREATION_RESERVATION_STOLEN",
  PROJECT_CREATION_DB_CONFLICT: "PROJECT_CREATION_DB_CONFLICT",

  // Whiteboard: WebSocket Events
  NOT_SUBSCRIBED: "NOT_SUBSCRIBED",
  BOARD_LOCKED: "BOARD_LOCKED",
  INVALID_ENCODING: "INVALID_ENCODING",
  UPDATE_TOO_LARGE: "UPDATE_TOO_LARGE",
  INVALID_YJSUPDATE: "INVALID_YJSUPDATE",

  // Shared: Locking Service
  LOCK_ERROR: "LOCK_ERROR",
  LOCK_FINALIZE_FAILED: "LOCK_FINALIZE_FAILED",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
