export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CLERK_ID_MISMATCH: "CLERK_ID_MISMATCH",
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  CONFLICT: "CONFLICT",
  RESERVATION_INVALID: "RESERVATION_INVALID",
  SLUG_TAKEN: "SLUG_TAKEN",
  IDEMPOTENCY_LOCKED: "IDEMPOTENCY_LOCKED",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",

  // Workspace: Slug Service
  WORKSPACE_SLUG_RATE_LIMITED: "WORKSPACE_SLUG_RATE_LIMITED",
  WORKSPACE_SLUG_TAKEN_PERMANENT: "WORKSPACE_SLUG_TAKEN_PERMANENT",
  WORKSPACE_SLUG_TAKEN_RESERVED: "WORKSPACE_SLUG_TAKEN_RESERVED",
  WORKSPACE_SLUG_RESERVATION_FAILED: "WORKSPACE_SLUG_RESERVATION_FAILED",

  // Workspace: Creation Service
  WORKSPACE_CREATION_RESERVATION_MISSING:
    "WORKSPACE_CREATION_RESERVATION_MISSING",
  WORKSPACE_CREATION_RESERVATION_STOLEN:
    "WORKSPACE_CREATION_RESERVATION_STOLEN",
  WORKSPACE_CREATION_DB_CONFLICT: "WORKSPACE_CREATION_DB_CONFLICT",
  WORKSPACE_CREATION_QUOTA_EXCEEDED: "WORKSPACE_CREATION_QUOTA_EXCEEDED",

  // Workspace: Onboarding Service
  WORKSPACE_ONBOARDING_ALREADY_EXISTS: "WORKSPACE_ONBOARDING_ALREADY_EXISTS",
  WORKSPACE_ONBOARDING_SLUG_GENERATION_FAILED:
    "WORKSPACE_ONBOARDING_SLUG_GENERATION_FAILED",
  WORKSPACE_ONBOARDING_CUSTOM_SLUG_TAKEN:
    "WORKSPACE_ONBOARDING_CUSTOM_SLUG_TAKEN",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
