export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CLERK_ID_MISMATCH: "CLERK_ID_MISMATCH",
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
