services:
  postgres:
    image: postgres:16-alpine
    container_name: collabify-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-collabify}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"] # Helpful for debugging dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: collabify-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: openresty/openresty:alpine
    container_name: collabify-nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_ENV=dev
      - BACKEND_HOST=host.docker.internal
      - BACKEND_PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ALLOWED_ORIGIN=http://localhost
      - ENABLE_RATE_LIMIT=false
      - ENABLE_ORIGIN_CHECK=false
      - LOG_LEVEL=notice

    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - redis
    networks:
      - collabify-net

networks:
  collabify-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:

# sudo docker compose up -d
# sudo docker compose up
# sudo docker exec -it collabify-postgres psql -U postgres -d collabify
